version: "3.8"

services:
  tests:
    command: python -m pytest app/tests/
    environment:
      - TSS_ENDPOINT=http://localhost:14141
    build: ./groundcontrol-api
  script-test:
    command: tail -F anything
    build: ./test_scripts # use latest official postgres version

